app:
  service:
    type: "basic"
  jwt:
    secret: "F811B1184C98D8543B1351D939484"
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

discodeit:
  storage:
    type: local
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:.discodeit/storage}
    s3:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
      region: ${AWS_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}


decorator:
  datasource:
    p6spy:
      enable-logging: true

spring:
  application:
    name: discodeit
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        default_batch_fetch_size: 100
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  boot:
    admin:
      client:
        instance:
          name: discodeit

management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "info"
          - "metrics"
          - "loggers"
          - "beans"
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Discodeit
    version: 1.7.0
  java:
    version: 17
  spring-boot:
    version: 3.4.0



logging:
  level:
    p6spy: INFO
    root: INFO



springdoc:
  default-flat-param-object: true
  api-docs:
    path: /api-docs  # OpenAPI 문서 접근 경로
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로 (기본값)

#    url: /apiV2.json


