spring:
  application:
    name: discodeit
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
  boot:
    admin:
      client:
        url: http://localhost:9090


logging:
  level:
    p6spy: DEBUG
    root: DEBUG
server:
  port: 8080
