spring:
  application:
    name: discodeit
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver



logging:
  level:
    p6spy: ERROR
    root: ERROR
server:
  port: 8081
