spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234

logging:
  level:
    p6spy: ERROR
    root: INFO
server:
  port: 8082
