app:
  service:
    type: "basic"

discodeit:
  storage:
    type: "local"
    local:
      root-path: "${user.dir}/sprint-mission"

decorator:
  datasource:
    p6spy:
      enable-logging: true

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
        default_batch_fetch_size: 100
    open-in-view: false


logging:
  level:
    p6spy: DEBUG
    root: INFO


springdoc:
  default-flat-param-object: true
  api-docs:
    path: /api-docs  # OpenAPI 문서 접근 경로
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로 (기본값)
    url: /apiV2.json

