name: CI on Push

on:
  push:
    branches:
      - part3-허지웅-sprint8


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grand execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and Test with Gradle
        run: ./gradlew clean test -x checkstyleMain -x checkstyleTest
